name: hello-world-service
version: 0.1
summary: A hello world style nodejs app
description: 
  This example nodejs application that says hello to you.
  This code is part the snapcraft example tour at
  https://developer.ubuntu.com/snapcraft-getting-started
confinement: devmode

apps:
  hello-service:
    command: hello-world
    daemon: simple

parts:
  hello:
    plugin: nodejs
    source: .
